#!/usr/bin/env bash

set -Eeuo pipefail

readonly REPO_NAME="fedora-config"
readonly DOT_DIR="$HOME/.${REPO_NAME}"

log() {
  printf "\033[1;34mℹ\033[0m %s\n" "$*"
}

error() {
  printf "\033[1;31m✖\033[0m %s\n" "$*" >&2
}

die() {
  error "$*"
  exit 1
}

has_cmd() {
  command -v "$1" >/dev/null 2>&1
}

main() {
  has_cmd dnf || die "Only Fedora is supported. Quitting."
  sudo dnf install -y git-core curl fish

  log "Fedora Config Setup..."

  if [ ! -d "$DOT_DIR" ]; then
    git clone https://github.com/pervezfunctor/fedora-config "$DOT_DIR" || die "git clone failed"
  fi

  [ -d "$DOT_DIR" ] || die "$DOT_DIR directory not found. Quitting."

  if ! has_cmd nix; then
    if ! has_cmd /nix/var/nix/profiles/default/bin/nix; then
      curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --determinate --no-confirm
    fi
    source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
  fi

  has_cmd nix || die "nix is not installed. Quitting."

  trash ~/.config/fish/config.fish
  ln -sf "$DOT_DIR/config/fish/config.fish" ~/.config/fish/config.fish
  sudo chsh -s /usr/bin/fish "$USER"
  has_cmd starship || curl -sS https://starship.rs/install.sh | sh

  echo ""
  log "Shell configuration complete."
  log "Use nix run nixpkgs#nushell -- ~/.fedora-config/scripts/setup.nu for further setup."
  echo ""
}

main "$@"
